### ISSUE TITLE
Playing replays after map change doesn't teleport client to initial position

### ISSUE THREAD

**Issue by splewis** [peace-maker/botmimic#10]
I'm getting this behavior consistently (CS:GO). Roughly what I'm doing is (with the botmimic_menu plugin):

- open the bot mimic menu via !admin
- record me running around and throwing a smoke grenade, shooting a gun, doing whatever
- adding a bot to replay that, works succesfully
- changing the map to the same map (or ``sm plugins reload botmimic``)
- adding a bot again and telling him to run the replay I just recorded

This results in the bot teleporting to the 0 0 0 origin point. Spectating it still shows it moving around (and getting the right weapons, shooting when I did, etc.) like there is still data being read - but something is wrong with the replay after a mapchange.  

From adding cursory log messages around the plugin I can't figure out why it works originally but then not after a map change or plugin reload.

Tested using:
botmimic @ 1b72b5c5a4548631b59046d682b72588c65f4b34
sourcemod @ 1.9.0.6222

**Comment by peace-maker** [comment]
Which compiler version did you use? There's a bug that was just fixed recentlyish.
https://github.com/alliedmodders/sourcepawn/issues/126

**Comment by splewis** [comment]
Looks like I was compiling with:
```
SourcePawn Compiler 1.9.0.5958
```

Welp. 

Tried a newer compiler version, it worked. Thanks!
