### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by sneak-it** [peace-maker/botmimic#8]
```
L 03/18/2016 - 00:16:42: SourceMod error session started
L 03/18/2016 - 00:16:42: Info (map "bhop_impecible_csgo") (file "errors_20160318.log")
L 03/18/2016 - 00:16:42: [SM] Native "CloseHandle" reported: Handle 64ba0762 is invalid (error 1)
L 03/18/2016 - 00:16:42: [SM] Displaying call stack trace for plugin "botmimic.smx":
L 03/18/2016 - 00:16:42: [SM]   [0]  Line 278, G:\addons\sourcemod\scripting\botmimic.sp::OnMapStart()
L 03/18/2016 - 00:20:06: Error log file session closed.
```

Seems to happen quite often, last night I was running through maps and this error was popping every map.

**Comment by peace-maker** [comment]
I've cleaned up some of the handle management just now. I couldn't see how there might be a double free yet, but maybe it already helped with this.

**Comment by blackhawk74** [comment]
Much appreciated, I will test the latest version and return with my findings!

**Comment by peace-maker** [comment]
Haven't heared of this anymore, you can reopen if you still have problems.
